FROM nvidia/cuda:11.6.2-devel-ubuntu20.04
# FROM continuumio/anaconda3:2024.02-1


SHELL ["/bin/bash", "-c"]

# apt-get install -y python3.10 python3-pip build-essential wget ninja-build unzip libgl-dev ffmpeg && \


ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y python3.7 python3-pip build-essential wget ninja-build unzip libgl-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# RUN pip install torch


RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && /bin/bash ~/miniconda.sh -b -p /opt/conda

ENV PATH="/opt/conda/bin:$PATH"

WORKDIR /gaussian-splatting
COPY ./ ./
COPY ./gaussian-splatting/environment.yml environment.yml

ENV TORCH_CUDA_ARCH_LIST="3.5;5.0;6.0;6.1;7.0;7.5;8.0;8.6+PTX"

RUN conda update -n base conda
RUN conda install -n base conda-libmamba-solver
RUN conda config --set solver libmamba
# RUN conda install -n base libarchive -c main --force-reinstall
RUN conda env create -f environment.yml
# RUN conda init bash

# RUN conda config --append channels conda-forge

# SHELL ["conda", "run", "-n", "gaussian_splatting", "/bin/bash", "-c"]
# RUN conda install colmap -c conda-forge
# RUN conda remove ffmpeg -y

RUN conda install pytorch torchvision -c pytorch


# RUN conda env create --file environment.yml
# RUN conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 pytorch-cuda=11.7 -c pytorch -c nvidia -c conda-forge
# RUN conda activate gaussian_splatting

# RUN conda install pytorch==1.12.1

# WORKDIR /

CMD ["python3", "train.py", "-s", "test_images/"]

# ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "gaussian_splatting", "jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--allow-root"]
